import { CopilotUsage } from "@/features/common/models";

export const sampleData: CopilotUsage[] = [
  {
    total_active_users: 250,
    total_engaged_users: 230,
    total_ide_engaged_users: 240,
    total_code_suggestions: 15450,
    total_code_acceptances: 9845,
    total_code_lines_suggested: 12945,
    total_code_lines_accepted: 7456,
    total_chat_engaged_users: 227,
    total_chats: 3487,
    total_chat_insertion_events: 3523,
    total_chat_copy_events: 16534,
    day: "2025-01-08",
    breakdown: [
      {
        language: "C#",
        model: "default",
        editor: "vs",
        suggestions_count: 25,
        acceptances_count: 20,
        lines_suggested: 50,
        lines_accepted: 40,
        active_users: 2,
      },
      {
        language: "typescript",
        model: "default",
        editor: "vscode",
        suggestions_count: 25,
        acceptances_count: 20,
        lines_suggested: 50,
        lines_accepted: 40,
        active_users: 2,
      },
    ],
  },
  {
    total_active_users: 250,
    total_engaged_users: 230,
    total_ide_engaged_users: 240,
    total_code_suggestions: 15450,
    total_code_acceptances: 9845,
    total_code_lines_suggested: 12945,
    total_code_lines_accepted: 7456,
    total_chat_engaged_users: 227,
    total_chats: 3487,
    total_chat_insertion_events: 3523,
    total_chat_copy_events: 16534,
    day: "2025-01-07",
    breakdown: [
      {
        language: "C#",
        model: "default",
        editor: "vs",
        suggestions_count: 10,
        acceptances_count: 5,
        lines_suggested: 10,
        lines_accepted: 5,
        active_users: 5,
      },
      {
        language: "typescript",
        model: "default",
        editor: "vscode",
        suggestions_count: 20,
        acceptances_count: 10,
        lines_suggested: 30,
        lines_accepted: 10,
        active_users: 5,
      },
    ],
  },
];
